// Generated by llvm2cpp - DO NOT MODIFY!

#include <llvm/Pass.h>
#include <llvm/PassManager.h>
#include <llvm/ADT/SmallVector.h>
#include <llvm/IR/Verifier.h>
#include <llvm/IR/BasicBlock.h>
#include <llvm/IR/CallingConv.h>
#include <llvm/IR/Constants.h>
#include <llvm/IR/DerivedTypes.h>
#include <llvm/IR/Function.h>
#include <llvm/IR/GlobalVariable.h>
#include <llvm/IR/IRPrintingPasses.h>
#include <llvm/IR/InlineAsm.h>
#include <llvm/IR/Instructions.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>
#include <llvm/Support/FormattedStream.h>
#include <llvm/Support/MathExtras.h>

using namespace llvm;


Module* makeLLVMModule() {
 // Module Construction
 Module* mod = new Module("debug.ll", getGlobalContext());
 mod->setTargetTriple("x86_64-apple-macosx10.10.0");
 
 // Type Definitions
    LLVMContext &ctx = mod->getContext();
    ArrayType* ArrayTy_0 = ArrayType::get(IntegerType::get(ctx, 8), 7);
 
 PointerType* PointerTy_1 = PointerType::get(ArrayTy_0, 0);
 
 std::vector<Type*> FuncTy_2_args;
 FunctionType* FuncTy_2 = FunctionType::get(
  /*Result=*/IntegerType::get(ctx, 32),
  /*Params=*/FuncTy_2_args,
  /*isVarArg=*/false);
 
 PointerType* PointerTy_3 = PointerType::get(IntegerType::get(ctx, 32), 0);
 
 PointerType* PointerTy_4 = PointerType::get(IntegerType::get(ctx, 8), 0);
 
 std::vector<Type*> FuncTy_6_args;
 FuncTy_6_args.push_back(PointerTy_4);
 FunctionType* FuncTy_6 = FunctionType::get(
  /*Result=*/IntegerType::get(ctx, 32),
  /*Params=*/FuncTy_6_args,
  /*isVarArg=*/true);
 
 PointerType* PointerTy_5 = PointerType::get(FuncTy_6, 0);
 
 
 // Function Declarations
 
 Function* func_main = mod->getFunction("main");
 if (!func_main) {
 func_main = Function::Create(
  /*Type=*/FuncTy_2,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"main", mod); 
 func_main->setCallingConv(CallingConv::C);
 }

 Function* func_printf = mod->getFunction("printf");
 if (!func_printf) {
 func_printf = Function::Create(
  /*Type=*/FuncTy_6,
  /*Linkage=*/GlobalValue::ExternalLinkage,
  /*Name=*/"printf", mod); // (external, no body)
 func_printf->setCallingConv(CallingConv::C);
 }

 // Global Variable Declarations

 
 GlobalVariable* gvar_array__str = new GlobalVariable(/*Module=*/*mod, 
 /*Type=*/ArrayTy_0,
 /*isConstant=*/true,
 /*Linkage=*/GlobalValue::PrivateLinkage,
 /*Initializer=*/0, // has initializer, specified below
 /*Name=*/".str");
 gvar_array__str->setAlignment(1);
 
 // Constant Definitions
 Constant *const_array_7 = ConstantDataArray::getString(ctx, "Hello\n", true);
 ConstantInt* const_int32_8 = ConstantInt::get(ctx, APInt(32, StringRef("1"), 10));
 ConstantInt* const_int32_9 = ConstantInt::get(ctx, APInt(32, StringRef("0"), 10));
 std::vector<Constant*> const_ptr_10_indices;
 const_ptr_10_indices.push_back(const_int32_9);
 const_ptr_10_indices.push_back(const_int32_9);
 Constant* const_ptr_10 = ConstantExpr::getGetElementPtr(gvar_array__str, const_ptr_10_indices);
 
 // Global Variable Definitions
 gvar_array__str->setInitializer(const_array_7);
 
 // Function Definitions
 
 // Function: main (func_main)
 {
  
  BasicBlock* label_11 = BasicBlock::Create(ctx, "",func_main,0);
  
  // Block  (label_11)
  AllocaInst* ptr_12 = new AllocaInst(IntegerType::get(ctx, 32), "", label_11);
  ptr_12->setAlignment(4);
  StoreInst* void_13 = new StoreInst(const_int32_9, ptr_12, false, label_11);
  CallInst* int32_14 = CallInst::Create(func_printf, const_ptr_10, "", label_11);
  int32_14->setCallingConv(CallingConv::C);
  int32_14->setTailCall(false);
  AttributeSet int32_14_PAL;
  int32_14->setAttributes(int32_14_PAL);
  
  ReturnInst::Create(ctx, const_int32_9, label_11);
  
 }
 
 return mod;
}

int main(int argc, char**argv) {
    makeLLVMModule();
//  Module* Mod = makeLLVMModule();
//  verifyModule(*Mod);
//  PassManager PM;
//  PM.add(createPrintModulePass( outs() ));
//  PM.run(*Mod);
    return 0;
}

